football:
  instanceId: ${random.int}
server:
  port: 0
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: FootballServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}