management:
  tracing:
    sampling:
      probability: 0.0
    endpoint:
      health:
        probes:
            enabled: true
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football,prometheus
football:
    folder: ../../teams

spring:
  application:
    name: trading-service
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: packt
    password: packt