server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: bindings, health, info, metrics, env, beans, loggers
spring:
  application:
    name: score

  rabbitmq:
    host: localhost
    username: packt
    password: packt
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input1:
            consumer:
              bindingRoutingKey: football.goal.#
              auto-bind-dlq: true
              max-attempts: 3
              ttl: 1000
      function:
        # routing: enabled
        bindings:
          processGoals-in-0: input1
        # routing-expression: headers['eventType']
      bindings:
        input1:
          destination: match-events-topic
          group: score
          # bindingRoutingKey: football.goal.#
          # exchangeType: direct
          # binder: rabbit

