server:
  port: 0

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: AlbumsServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
